#!/usr/bin/bash

ANSI_RESET="\033[0m"
ANSI_WHITE="\033[37m"

 echo -e "${ANSI_RESET}IS THIS LINE VISIBLE?"
 echo -e "${ANSI_RESET}\n${ANSI_WHITE}HOW ABOUT THIS ONE?${ANSI_RESET}\nOR THIS?${ANSI_RESET}"

